//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship.
        /// </summary>
        public static string StringChampionship {
            get {
                return ResourceManager.GetString("StringChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian (Hrvatski).
        /// </summary>
        public static string StringLangCroatian {
            get {
                return ResourceManager.GetString("StringLangCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Engleski).
        /// </summary>
        public static string StringLangEnglish {
            get {
                return ResourceManager.GetString("StringLangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string StringLanguage {
            get {
                return ResourceManager.GetString("StringLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men&apos;s.
        /// </summary>
        public static string StringMens {
            get {
                return ResourceManager.GetString("StringMens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string StringSave {
            get {
                return ResourceManager.GetString("StringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string StringSettings {
            get {
                return ResourceManager.GetString("StringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women&apos;s.
        /// </summary>
        public static string StringWomens {
            get {
                return ResourceManager.GetString("StringWomens", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favourite Team.
        /// </summary>
        public static string StringFavouriteTeam {
            get {
                return ResourceManager.GetString("StringFavouriteTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string StringLoading {
            get {
                return ResourceManager.GetString("StringLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rankings.
        /// </summary>
        public static string StringRankings {
            get {
                return ResourceManager.GetString("StringRankings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Goal Scorers.
        /// </summary>
        public static string StringGoalScorers {
            get {
                return ResourceManager.GetString("StringGoalScorers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards.
        /// </summary>
        public static string StringYellowCards {
            get {
                return ResourceManager.GetString("StringYellowCards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string StringAttendance {
            get {
                return ResourceManager.GetString("StringAttendance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string StringPlayer {
            get {
                return ResourceManager.GetString("StringPlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string StringGoals {
            get {
                return ResourceManager.GetString("StringGoals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string StringCards {
            get {
                return ResourceManager.GetString("StringCards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string StringLocation {
            get {
                return ResourceManager.GetString("StringLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        public static string StringMatch {
            get {
                return ResourceManager.GetString("StringMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Rankings.
        /// </summary>
        public static string StringViewRankings {
            get {
                return ResourceManager.GetString("StringViewRankings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Player Images.
        /// </summary>
        public static string StringPlayerImages {
            get {
                return ResourceManager.GetString("StringPlayerImages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Player Images.
        /// </summary>
        public static string StringManagePlayerImages {
            get {
                return ResourceManager.GetString("StringManagePlayerImages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse Image....
        /// </summary>
        public static string StringBrowseImage {
            get {
                return ResourceManager.GetString("StringBrowseImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove Image.
        /// </summary>
        public static string StringRemoveImage {
            get {
                return ResourceManager.GetString("StringRemoveImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No image assigned.
        /// </summary>
        public static string StringNoImageAssigned {
            get {
                return ResourceManager.GetString("StringNoImageAssigned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a player from the list.
        /// </summary>
        public static string StringSelectPlayer {
            get {
                return ResourceManager.GetString("StringSelectPlayer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string StringImageFiles {
            get {
                return ResourceManager.GetString("StringImageFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fetch from API.
        /// </summary>
        public static string StringFetchFromApi {
            get {
                return ResourceManager.GetString("StringFetchFromApi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string StringCaptain {
            get {
                return ResourceManager.GetString("StringCaptain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        public static string StringFavourite {
            get {
                return ResourceManager.GetString("StringFavourite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favourite Players.
        /// </summary>
        public static string StringFavouritePlayers {
            get {
                return ResourceManager.GetString("StringFavouritePlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other Players.
        /// </summary>
        public static string StringOtherPlayers {
            get {
                return ResourceManager.GetString("StringOtherPlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add to Favourites.
        /// </summary>
        public static string StringAddToFavourites {
            get {
                return ResourceManager.GetString("StringAddToFavourites", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove from Favourites.
        /// </summary>
        public static string StringRemoveFromFavourites {
            get {
                return ResourceManager.GetString("StringRemoveFromFavourites", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum of 3 favourite players allowed.
        /// </summary>
        public static string StringMaxFavouritesReached {
            get {
                return ResourceManager.GetString("StringMaxFavouritesReached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Favourite Players.
        /// </summary>
        public static string StringSelectFavouritePlayers {
            get {
                return ResourceManager.GetString("StringSelectFavouritePlayers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drag players between panels, double-click, or use context menu to manage..
        /// </summary>
        public static string StringDragDropInstructions {
            get {
                return ResourceManager.GetString("StringDragDropInstructions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application?.
        /// </summary>
        public static string StringCloseConfirmation {
            get {
                return ResourceManager.GetString("StringCloseConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string StringPrint {
            get {
                return ResourceManager.GetString("StringPrint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No data available to print..
        /// </summary>
        public static string StringNoDataToPrint {
            get {
                return ResourceManager.GetString("StringNoDataToPrint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print / Export.
        /// </summary>
        public static string StringPrintExport {
            get {
                return ResourceManager.GetString("StringPrintExport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string StringError {
            get {
                return ResourceManager.GetString("StringError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string StringSuccess {
            get {
                return ResourceManager.GetString("StringSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string StringWarning {
            get {
                return ResourceManager.GetString("StringWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string StringConfirm {
            get {
                return ResourceManager.GetString("StringConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string StringCancel {
            get {
                return ResourceManager.GetString("StringCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string StringYes {
            get {
                return ResourceManager.GetString("StringYes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string StringNo {
            get {
                return ResourceManager.GetString("StringNo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No teams available.
        /// </summary>
        public static string StringNoTeamsAvailable {
            get {
                return ResourceManager.GetString("StringNoTeamsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to load teams. Check your connection..
        /// </summary>
        public static string StringErrorLoadingTeams {
            get {
                return ResourceManager.GetString("StringErrorLoadingTeams", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings saved..
        /// </summary>
        public static string StringSettingsSaved {
            get {
                return ResourceManager.GetString("StringSettingsSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to save settings..
        /// </summary>
        public static string StringErrorSavingSettings {
            get {
                return ResourceManager.GetString("StringErrorSavingSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No favourite team selected..
        /// </summary>
        public static string StringNoFavouriteTeam {
            get {
                return ResourceManager.GetString("StringNoFavouriteTeam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a favourite team first..
        /// </summary>
        public static string StringSelectFavouriteTeamFirst {
            get {
                return ResourceManager.GetString("StringSelectFavouriteTeamFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string StringContinueQuestion {
            get {
                return ResourceManager.GetString("StringContinueQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image assigned..
        /// </summary>
        public static string StringImageAssigned {
            get {
                return ResourceManager.GetString("StringImageAssigned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image removed..
        /// </summary>
        public static string StringImageRemoved {
            get {
                return ResourceManager.GetString("StringImageRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to load image..
        /// </summary>
        public static string StringErrorLoadingImage {
            get {
                return ResourceManager.GetString("StringErrorLoadingImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matches found..
        /// </summary>
        public static string StringNoMatchesFound {
            get {
                return ResourceManager.GetString("StringNoMatchesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to load data..
        /// </summary>
        public static string StringErrorLoadingData {
            get {
                return ResourceManager.GetString("StringErrorLoadingData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Favourites saved..
        /// </summary>
        public static string StringFavouritesSaved {
            get {
                return ResourceManager.GetString("StringFavouritesSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Save before closing?.
        /// </summary>
        public static string StringUnsavedChanges {
            get {
                return ResourceManager.GetString("StringUnsavedChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove this item?.
        /// </summary>
        public static string StringRemoveConfirmation {
            get {
                return ResourceManager.GetString("StringRemoveConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Display Mode.
        /// </summary>
        public static string StringDisplayMode {
            get {
                return ResourceManager.GetString("StringDisplayMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string StringResolution {
            get {
                return ResourceManager.GetString("StringResolution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string StringFullscreen {
            get {
                return ResourceManager.GetString("StringFullscreen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Windowed.
        /// </summary>
        public static string StringWindowed {
            get {
                return ResourceManager.GetString("StringWindowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string StringOpponent {
            get {
                return ResourceManager.GetString("StringOpponent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Player not found. Try using Browse Image..
        /// </summary>
        public static string StringPlayerNotFound {
            get {
                return ResourceManager.GetString("StringPlayerNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No image available for this player..
        /// </summary>
        public static string StringNoImageAvailable {
            get {
                return ResourceManager.GetString("StringNoImageAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network error. Check your connection..
        /// </summary>
        public static string StringNetworkError {
            get {
                return ResourceManager.GetString("StringNetworkError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Request timed out. Try again later..
        /// </summary>
        public static string StringTimeoutError {
            get {
                return ResourceManager.GetString("StringTimeoutError", resourceCulture);
            }
        }
    }
}
